version: "3.8"

services:  
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
